---
# tasks file for role_vmrun
- block:
    - name: "({{ ROLE_ID }} - 000.01) To execute vmrun command"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun -T {{ vmrun_type }} {{ vmrun_state }} "{{ item }}" {{ vmrun_start_parameter }} {{ vmrun_stop_parameter }} {{ vmrun_clone_parameter }}
      args:
          executable: /bin/bash
      loop: "{{ vmx_start_list | list + vmx_stop_list | list + vmx_clone_list | list }}"
  when: vmx_stop_list != "all"

- name: stop all VMs
  block:
    - name: "({{ ROLE_ID }} - 000.02) To get vmrun list"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun list | grep -vi "tower\|total running vms"
      args:
          executable: /bin/bash
      register: listIsAll

    - name: "({{ ROLE_ID }} - 000.03) To execute vmrun for all"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun -T {{ vmrun_type }} stop "{{ item }}" {{ vmrun_stop_parameter }}
      args:
          executable: /bin/bash
      loop: "{{ listIsAll.stdout_lines }}"
  when: vmx_stop_list == "all"
