---
# tasks file for role_vmrun
- block:
    - name: "({{ ROLE_ID }} - 000.01) To execute vmrun command"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun -T {{ vmrun_type }} {{ vmrun_state }} "{{ vmx_directory }}{{ item }}" {{ vmrun_parameter }}
      args:
          executable: /bin/bash
      loop: "{{ vmx_file_list | list }}"
  when: vmx_file_list != "all"

- block:
    - name: "({{ ROLE_ID }} - 000.02) To get vmrun list"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun list | grep -vi "tower\|total running vms" |sed 's!{{ vmx_directory }}!!g'
      args:
          executable: /bin/bash
      register: listIsAll

    - name: "({{ ROLE_ID }} - 000.03) To execute vmrun for all"
      shell: >
          cd "{{ vmrun_path }}" && ./vmrun -T {{ vmrun_type }} {{ vmrun_state }} "{{ vmx_directory }}{{ item }}" {{ vmrun_parameter }}
      args:
          executable: /bin/bash
      loop: "{{ listIsAll.stdout_lines }}"
  when: vmx_file_list == "all"
